-- Generated by Oracle SQL Developer Data Modeler 17.2.0.188.1104
--   at:        2017-12-27 00:06:08 CET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE TABLE bannedmacs (
    macid              INTEGER NOT NULL,
    mac                CHAR(12 CHAR) NOT NULL,
    configs_configid   INTEGER NOT NULL
);

ALTER TABLE bannedmacs ADD CONSTRAINT bannedmacs_pk PRIMARY KEY ( macid );

CREATE TABLE configs (
    configid                       INTEGER NOT NULL,
    networkgroups_networkgroupid   INTEGER NOT NULL,
    users_username                 VARCHAR2(100 CHAR) NOT NULL,
    networks_networkid             INTEGER NOT NULL
);

CREATE UNIQUE INDEX configs__idx ON
    configs ( users_username ASC );

ALTER TABLE configs ADD CONSTRAINT configs_pk PRIMARY KEY ( configid );

CREATE TABLE groups (
    groupid          INTEGER NOT NULL,
    name             VARCHAR2(255 CHAR) NOT NULL,
    data             CLOB NOT NULL,
    users_username   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE groups ADD CONSTRAINT groups_pk PRIMARY KEY ( groupid );

CREATE TABLE logs (
    logid            INTEGER NOT NULL,
    type             SMALLINT NOT NULL,
    description      VARCHAR2(255 CHAR) NOT NULL,
    users_username   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE logs ADD CONSTRAINT logs_pk PRIMARY KEY ( logid );

CREATE TABLE networkgroups (
    networkgroupid   INTEGER NOT NULL,
    name             VARCHAR2(255 CHAR) NOT NULL,
    users_username   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE networkgroups ADD CONSTRAINT networkgroups_pk PRIMARY KEY ( networkgroupid );

CREATE TABLE networks (
    networkid                      INTEGER NOT NULL,
    ssid                           VARCHAR2(255 CHAR) NOT NULL,
    password                       VARCHAR2(255 CHAR) NOT NULL,
    type                           NUMBER NOT NULL,
    networkgroups_networkgroupid   INTEGER
);

ALTER TABLE networks ADD CONSTRAINT networks_pk PRIMARY KEY ( networkid );

CREATE TABLE pastes (
    pasteid          INTEGER NOT NULL,
    data             CLOB NOT NULL,
    title            VARCHAR2(255 CHAR),
    timestamp        TIMESTAMP NOT NULL,
    extended         NUMBER NOT NULL,
    users_username   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE pastes ADD CONSTRAINT pastes_pk PRIMARY KEY ( pasteid );

CREATE TABLE performances (
    performanceid        INTEGER NOT NULL,
    uploadspeed          NUMBER NOT NULL,
    "Date"               DATE NOT NULL,
    downloadspeed        NUMBER NOT NULL,
    networks_networkid   INTEGER NOT NULL
);

ALTER TABLE performances ADD CONSTRAINT performances_pk PRIMARY KEY ( performanceid );

CREATE TABLE sessions (
    sesisonid        INTEGER NOT NULL,
    data             VARCHAR2(255 CHAR) NOT NULL,
    users_username   VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE sessions ADD CONSTRAINT sessions_pk PRIMARY KEY ( sesisonid );

CREATE TABLE users (
    username       VARCHAR2(100 CHAR) NOT NULL,
    passwordhash   VARCHAR2(255 CHAR) NOT NULL,
    passwordsalt   VARCHAR2(32 CHAR) NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( username );

ALTER TABLE bannedmacs
    ADD CONSTRAINT bannedmacs_configs_fk FOREIGN KEY ( configs_configid )
        REFERENCES configs ( configid );

ALTER TABLE configs
    ADD CONSTRAINT configs_networkgroups_fk FOREIGN KEY ( networkgroups_networkgroupid )
        REFERENCES networkgroups ( networkgroupid );

ALTER TABLE configs
    ADD CONSTRAINT configs_networks_fk FOREIGN KEY ( networks_networkid )
        REFERENCES networks ( networkid );

ALTER TABLE configs
    ADD CONSTRAINT configs_users_fk FOREIGN KEY ( users_username )
        REFERENCES users ( username );

ALTER TABLE groups
    ADD CONSTRAINT groups_users_fk FOREIGN KEY ( users_username )
        REFERENCES users ( username );

ALTER TABLE logs
    ADD CONSTRAINT logs_users_fk FOREIGN KEY ( users_username )
        REFERENCES users ( username );

ALTER TABLE networkgroups
    ADD CONSTRAINT networkgroups_users_fk FOREIGN KEY ( users_username )
        REFERENCES users ( username );

ALTER TABLE networks
    ADD CONSTRAINT networks_networkgroups_fk FOREIGN KEY ( networkgroups_networkgroupid )
        REFERENCES networkgroups ( networkgroupid );

ALTER TABLE pastes
    ADD CONSTRAINT pastes_users_fk FOREIGN KEY ( users_username )
        REFERENCES users ( username );

ALTER TABLE performances
    ADD CONSTRAINT performances_networks_fk FOREIGN KEY ( networks_networkid )
        REFERENCES networks ( networkid );

ALTER TABLE sessions
    ADD CONSTRAINT sessions_users_fk FOREIGN KEY ( users_username )
        REFERENCES users ( username );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
